### ISSUE TITLE
add "allow"

### ISSUE THREAD

**Issue by jakecoffman** [jakecoffman/crud#1]
**Is your feature request related to a problem? Please describe.**

We can restrict strings with `Required` but there's no way to allow passing an empty string.

**Describe the solution you'd like**

Add `.Allow("")` to add this exception.

**Comment by beceqada32ps3** [comment]
```.Allow( "pr_request" )```

**Comment by beceqada32ps3** [comment]
> `.Allow( "pr_request" )`

We know about you @jakecoffman so we need to allow `main` but and allow `pr_request ` so let's merge `main` into this
