### ISSUE TITLE
Nested KindObjects not populated in the generated Swagger

### ISSUE THREAD

**Issue by matthewtylerwood** [jakecoffman/crud#12]
**Is your feature request related to a problem? Please describe.**
I noticed today nested object fields are not populated in the swagger output because of the following [TODO](https://github.com/jakecoffman/crud/blob/master/field.go#L486) in the code:
```
if field.kind == KindObject {
	// TODO
}
```

**Describe the solution you'd like**
Is this because of an issue you ran into? I was thinking about trying to take a stab at it, but I wasn't sure if you were currently working on it or had ideas about how you wanted to implement.

**Comment by jakecoffman** [comment]
I forgot about that, thanks for the reminder. It needs to be a recursive function. 

I probably can knock this out later today.

**Comment by jakecoffman** [comment]
@matthewtylerwood can you give me an example schema where this doesn't work?

**Comment by matthewtylerwood** [comment]
@jakecoffman Sure, let's say I create an endpoint with the following body validation:

```go
Validate: crud.Validate{
		Body: crud.Object(map[string]crud.Field{
			"testing": crud.Object(map[string]crud.Field{
				"testNestedField": crud.String().Pattern("[a-c]"),
			}),
		}),
	},
```

and then I hit the swagger and get:
```json
{
  "swagger": "2.0",
  "info": {
    "title": "Exchange API",
    "version": "1.0.0"
  },
  "paths": {
    "/test": {
      "post": {
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/Model-1"
            }
          }
        ],
        "responses": {
          "200": {
            "schema": {
              "type": "string"
            },
            "description": "OK"
          }
        },
        "description": "",
        "summary": ""
      }
    }
  },
  "definitions": {
    "Model-1": {
      "type": "object",
      "properties": {
        "testing": {
          "type": "object"
        }
      }
    }
  }
}
```

but what I'm expecting is the Model to instead look something like this:

```json
  "definitions": {
    "Model-1": {
      "type": "object",
      "properties": {
        "testing": {
          "type": "object",
          "properties": {
              "testNestedField": {
                  "type": "string",
                  "pattern": "[a-c]"
              }
          }
        }
      }
    }
  }
}
```

**Comment by jakecoffman** [comment]
Thanks, the TODO was a red herring and I got confused and wanted to make sure we were talking about the same issue. Looks like it's working now!
