### ISSUE TITLE
minLength and maxLength not supported for String fields

### ISSUE THREAD

**Issue by matthewtylerwood** [jakecoffman/crud#6]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to enforce a min and max character length on a string field.

**Describe the solution you'd like**
String fields should use `.Min()` and `.Max()` to enforce a character length on string fields.

This could look something like the following:

```
	case string:
		if f.kind != "string" {
			return errWrongType
		}
		if f.required != nil && *f.required && v == "" && !f.allow.has("") {
			return errRequired
		}

		// These checks would be new
		if f.max != nil && len(v) > *f.max {
			return errMaximum
		}
		if f.min != nil && len(v) < *f.min {
			return errMinimum
		}
```

**Comment by jakecoffman** [comment]
Thanks for reporting that, fixed!
