### ISSUE TITLE
Json Array in Body field of Validate does not return wrong type for Json Object

### ISSUE THREAD

**Issue by matthewtylerwood** [jakecoffman/crud#7]
**Describe the bug**

Validation of a json object body works, but validation of a json array body does not work.

**To reproduce the bug**

Create a validation spec similar to the following:

```
			Validate: crud.Validate{
				Body: crud.Array().Items(crud.String()),
			},
```

Then send a request body with something like `{}`. I would expect the error `body validation failed for field body: wrong type passed`, but no validation error occurs.

**Any other details**

On the flip side, passing a json array for a json object body does fail validation correctly. For example:

```
			Validate: crud.Validate{
				Body: crud.Object(map[string]crud.Field{
					"test": crud.String(),
				}),
			},
```

Then send a request body with something like `[]`. I get the following validation error:

```
body validation failed for field body: wrong type passed
```

which is what I would expect.

**Comment by jakecoffman** [comment]
Seems to work for me, I added a test and tried it live in this commit: https://github.com/jakecoffman/crud/commit/6bdee92ed3ea075caa18b816a6680acf16ac75f7

Are you using gin or another router?

**Comment by jakecoffman** [comment]
Oh, so there's a chance I fixed it on master in my last few commits there, so if you update to master it might fix it.

**Comment by matthewtylerwood** [comment]
Awesome, I just switched to the latest commit and that fixed it. I should have mentioned I was using v1.1.0, my bad.

Thanks for the quick reply!

**Comment by matthewtylerwood** [comment]
@jakecoffman just an FYI, I had to roll back to v1.1.0 and implement a work-around for checking json array types. When I updated to the latest master commit last night, some other things came up that I noticed such as:

1. Deeply nested unknown fields being stripped out of the request body even with `option.StripUnknown(false)`.
2. Required string inside an array no longer getting rejected when, for example, `{"test": [""]}` is sent in a request body.

I wasn't sure if you were still actively working on the new validation mechanics, so I wanted to pass these along in case you were unaware. I can try to get you some better test cases later if needed.

**Comment by jakecoffman** [comment]
Sorry about that, I'll try to sort it out.

**Comment by jakecoffman** [comment]
In 1f4b392408fdf56b2a9c06d27ca546fe61338fa7 my refactor broke how settings were applied so it only affected the top level object. Now fields inherit the strip/allow settings from the parent. This should have fixed the issues you saw, at least according to the tests!
